### PR TITLE
Adds a bit of fancy, restructures files page

### PR DESCRIPTION
**Pull request by ablwr**
There's more work to do but I don't want to get too far away and diverge from the master branch.

### CODE REVIEW

**Comment by ablwr** [comment]
@yayoiukai I will let you merge this in, I don't want to conflict with any of the work you are doing!

**Comment by dericed** [comment]
Looks SO good! I've been testing in Chrome, but in my Firefox it won't reveal the toolbar downdowns in File> Group> and Account>. Also if I force the width of the screen too small for the toolbar that = thing shows up, but it doesn't drop down on clicking. Works in chrome.

**Comment by ablwr** [comment]
Ooooh I forgot to go back and look at that! Will look now. It was working before/outside of the branch though, yeah? Guilty of Chrome-testing only.

**Comment by ablwr** [comment]
Dropdown works for me in Firefox! Including when I go tiny and get the 🍔 menu.

**Comment by ablwr** [comment]
Do you get any errors in your developer's console?

**Comment by ablwr** [comment]
OK, I will pause on working on this. It can be merged at anyone's leisure.

**Comment by dericed** [comment]
When I view source the only red line I see is "<link rel="stylesheet" type="text/css" href="/frontend/bower_components/datetimepicker/jquery.datetimepicker.css"/ >"

**Comment by ablwr** [comment]
Hmm. I don't get any. I am wondering if it is not compiling properly? Have you run every kind of configuration of quickstartdev.sh and frontend.sh? ;) I killed all my processes and ran quickstartdev.sh and things still seem to be functioning as normal.

**Pull request merged**
