### PR TITLE
Readme updates

### PR DESCRIPTION
**Pull request by dericed**

### CODE REVIEW

**Comment by dericed** [comment]
These 3 commits by were pushed directly to master. I rebased master and moved the commits to this PR to allow for review.

**Comment by dericed** [comment]
Commits 3938f6b and 520c914 null each other out (one is a change and then a revert to the change), so I dropped both commits and left the third.

**Comment by JeromeMartinez** [comment]
Commits should be merged in one before merge (edit: done)

signalserver or SignalServer? 
signalserver or signal server / Signal Server?
After these commits, there are "signalserver" (first word), "SignalServer" (second word just after the first word), "signal server", "Signal Server", and also "Signalsever", I suggest to decide about a form before changing it to different forms in a commit.
"Signalserver" when first word in a sentence, there is some debate about uppercase 1st letter for a proper name having no uppercase 1st letter, should it be with uppercase 1st letter or not? Good question...

**Comment by JeromeMartinez** [comment]
Commit message does not make sense.

**Comment by dericed** [comment]
closing without merge

**Pull request closed without merging**
